owner: PeterDaveHello
repo: ipinfo.tw-uptime

sites:
  - name: ipinfo.tw
    url: https://ipinfo.tw
    type: globalping
    
assignees:
  - PeterDaveHello

status-website:
  cname: uptime.ipinfo.tw
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ipinfo.tw service uptime
  introTitle: "Uptime page of ipinfo.tw"
  introMessage: This is the uptime page of ipinfo.tw
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/PeterDaveHello/ipinfo.tw

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
